# Generated by Django 3.2 on 2022-02-09 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActoJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_acto', models.CharField(max_length=100, unique=True, verbose_name='Acto Jurídico')),
            ],
            options={
                'verbose_name': 'Acto Jurídico',
                'verbose_name_plural': 'Actos Jurídicos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100, unique=True, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_etapa', models.CharField(max_length=150, verbose_name='Etapa')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=100, unique=True, verbose_name='Proyecto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.cliente', verbose_name='Cliente')),
                ('tramitador', models.ManyToManyField(db_index=True, related_name='tramitador', to=settings.AUTH_USER_MODEL, verbose_name='Tramitador')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoja_ruta', models.BigIntegerField(unique=True, verbose_name='Hoja Ruta')),
                ('fecha_reparto', models.DateField(help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', verbose_name='Fecha Reparto')),
                ('escritura', models.IntegerField(verbose_name='Número Escritura')),
                ('fecha_escritura', models.DateField(help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', verbose_name='Fecha Escritura')),
                ('canje', models.BooleanField(default=False, verbose_name='Para Canje')),
                ('activo', models.BooleanField(default=True, verbose_name='Reparto Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('editado', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edicion')),
                ('acto_juridico', models.ManyToManyField(db_index=True, related_name='acto_juridico', to='deed.ActoJuridico', verbose_name='Acto Jurídico')),
                ('protocolista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Asistente Escrituración')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Hoja de Ruta',
                'verbose_name_plural': 'Hojas de Ruta',
            },
        ),
        migrations.CreateModel(
            name='RepartoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', verbose_name='Fecha Inicio')),
                ('fecha_final', models.DateField(help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', verbose_name='Fecha Final')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.etapa', verbose_name='Etapa')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.reparto', verbose_name='Reparto')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateField(help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', verbose_name='Fecha Final')),
                ('reproceso', models.BooleanField(default=False, verbose_name='Hubo Reproceso')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('reparto_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.repartoetapa', verbose_name='Reparto - Etapa')),
            ],
            options={
                'verbose_name': 'Revisión',
                'verbose_name_plural': 'Revisiones',
            },
        ),
        migrations.CreateModel(
            name='OtorganteReparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(max_length=20, verbose_name='Número Factura')),
                ('derechos_notariales', models.DecimalField(decimal_places=1, max_digits=9, verbose_name='Derechos Notariales')),
                ('valor_registro', models.DecimalField(decimal_places=1, max_digits=9, verbose_name='Registro')),
                ('valor_rentas', models.DecimalField(decimal_places=1, max_digits=9, verbose_name='Rentas')),
                ('otorgante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Otorgante')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.reparto', verbose_name='Reparto')),
            ],
            options={
                'verbose_name': 'Otorgante',
                'verbose_name_plural': 'Otorgantes',
            },
        ),
        migrations.CreateModel(
            name='ObservacionEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=150, verbose_name='Observación')),
                ('reparto_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.repartoetapa', verbose_name='Reparto - Etapa')),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
            },
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmueble', models.CharField(help_text='Describa qué tipo de inmueble es.', max_length=150, verbose_name='Inmueble')),
                ('matricula', models.CharField(help_text='Ingrese el número de matrícula completo', max_length=150, verbose_name='Matricula Inmobiliaria')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.reparto', verbose_name='Reparto')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleta_rentas', models.CharField(max_length=20, verbose_name='Boleta Rentas')),
                ('fecha_boleta_rentas', models.DateField(help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', verbose_name='Fecha Boleta Rentas')),
                ('boleta_registro', models.CharField(max_length=20, verbose_name='Boleta Registro')),
                ('fecha_boleta_registro', models.DateField(help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', verbose_name='Fecha Boleta Registro')),
                ('reparto_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.repartoetapa', verbose_name='Reparto - Etapa')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
    ]
