# Generated by Django 3.2 on 2022-03-29 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actojuridico',
            options={'ordering': ['nombre_acto'], 'verbose_name': 'Acto Jurídico', 'verbose_name_plural': 'Actos Jurídicos'},
        ),
        migrations.AlterField(
            model_name='otorgantereparto',
            name='otorgante',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'otorgante'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Otorgante'),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='fecha_escritura',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Escritura'),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='protocolista',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'escrituracion'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Asistente Escrituración'),
        ),
    ]
