# Generated by Django 3.2 on 2022-03-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0002_auto_20220329_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otorgantereparto',
            name='canje',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Para Canje'),
        ),
        migrations.AlterField(
            model_name='otorgantereparto',
            name='derechos_notariales',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True, verbose_name='Derechos Notariales'),
        ),
        migrations.AlterField(
            model_name='otorgantereparto',
            name='factura',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Factura'),
        ),
        migrations.AlterField(
            model_name='otorgantereparto',
            name='valor_registro',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True, verbose_name='Registro'),
        ),
        migrations.AlterField(
            model_name='otorgantereparto',
            name='valor_rentas',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True, verbose_name='Rentas'),
        ),
    ]
