# Generated by Django 3.2 on 2022-02-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0002_auto_20220209_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparto',
            name='escritura',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número Escritura'),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='fecha_escritura',
            field=models.DateField(blank=True, help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Fecha Escritura'),
        ),
    ]
