# Generated by Django 3.2 on 2022-02-09 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0003_auto_20220209_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparto',
            name='fecha_reparto',
            field=models.DateField(default=django.utils.timezone.now, help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', verbose_name='Fecha Reparto'),
        ),
    ]
