# Generated by Django 3.2 on 2022-03-29 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20220326_1140'),
        ('deed', '0003_auto_20220329_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otorgantereparto',
            name='otorgante',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'otorgante'}, on_delete=django.db.models.deletion.CASCADE, to='registration.grantor', verbose_name='Otorgante'),
        ),
    ]
