# Generated by Django 3.2 on 2022-03-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0004_alter_otorgantereparto_otorgante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otorgantereparto',
            name='canje',
            field=models.BooleanField(default=False, verbose_name='Para Canje'),
        ),
    ]
