# Generated by Django 3.2 on 2022-02-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0004_alter_reparto_fecha_reparto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparto',
            name='fecha_reparto',
            field=models.DateField(help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', verbose_name='Fecha Reparto'),
        ),
    ]
