# Generated by Django 3.2 on 2022-02-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0005_alter_reparto_fecha_reparto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparto',
            name='canje',
        ),
        migrations.AddField(
            model_name='otorgantereparto',
            name='canje',
            field=models.BooleanField(default=False, verbose_name='Para Canje'),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
