# Generated by Django 3.2 on 2022-02-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0006_auto_20220220_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparto',
            name='anio_escritura',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='reparto',
            name='hoja_ruta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
