# Generated by Django 3.2 on 2022-02-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0007_auto_20220221_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparto',
            name='anio_escritura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='hoja_ruta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
