# Generated by Django 3.2 on 2022-02-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0008_auto_20220221_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparto',
            name='anio_escritura',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
