# Generated by Django 3.2 on 2022-02-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0009_alter_reparto_anio_escritura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparto',
            name='anio_escritura',
            field=models.CharField(blank=True, error_messages={'': ''}, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='escritura',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Número Escritura'),
        ),
    ]
