# Generated by Django 3.2 on 2022-03-29 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tramitador',
            field=models.ManyToManyField(db_index=True, limit_choices_to={'es_tramitador': True}, related_name='tramitador', to=settings.AUTH_USER_MODEL, verbose_name='Tramitador'),
        ),
    ]
