# Generated by Django 3.2 on 2022-03-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_proyecto_tramitador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre_cliente'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['nombre_proyecto'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
