# Generated by Django 3.2 on 2022-03-04 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_etapa', models.CharField(max_length=150, verbose_name='Etapa')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
            },
        ),
        migrations.CreateModel(
            name='RepartoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', verbose_name='Fecha Inicio')),
                ('fecha_final', models.DateField(help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', verbose_name='Fecha Final')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.etapa', verbose_name='Etapa')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.reparto', verbose_name='Reparto')),
            ],
            options={
                'verbose_name': 'Etapa Hoja Ruta',
                'verbose_name_plural': 'Etapas Hoja Ruta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateField(help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', verbose_name='Fecha Final')),
                ('reproceso', models.BooleanField(default=False, verbose_name='Hubo Reproceso')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('reparto_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.repartoetapa', verbose_name='Reparto - Etapa')),
            ],
            options={
                'verbose_name': 'Revisión',
                'verbose_name_plural': 'Revisiones',
            },
        ),
        migrations.CreateModel(
            name='ObservacionEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=150, verbose_name='Observación')),
                ('reparto_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.repartoetapa', verbose_name='Reparto - Etapa')),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleta_rentas', models.CharField(max_length=20, verbose_name='Boleta Rentas')),
                ('fecha_boleta_rentas', models.DateField(help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', verbose_name='Fecha Boleta Rentas')),
                ('boleta_registro', models.CharField(max_length=20, verbose_name='Boleta Registro')),
                ('fecha_boleta_registro', models.DateField(help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', verbose_name='Fecha Boleta Registro')),
                ('reparto_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.repartoetapa', verbose_name='Reparto - Etapa')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
    ]
