# Generated by Django 3.2 on 2022-03-20 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0005_auto_20220316_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repartoetapa',
            options={'ordering': ['id'], 'verbose_name': 'Etapa Hoja Ruta', 'verbose_name_plural': 'Etapas Hoja Ruta'},
        ),
    ]
