# Generated by Django 3.2 on 2022-03-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0007_auto_20220319_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacionetapa',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha-Hora-Observacion'),
        ),
    ]
