# Generated by Django 3.2 on 2022-03-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0008_alter_observacionetapa_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartoetapa',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
