# Generated by Django 3.2 on 2022-03-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0009_repartoetapa_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartoetapa',
            name='tipo_repartoetapa',
            field=models.CharField(choices=[('G', 'SELECCIONE'), ('I', 'RECEPCION'), ('R', 'EXTENCION')], default='G', max_length=1),
        ),
    ]
