# Generated by Django 3.2 on 2022-03-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0011_auto_20220320_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapa',
            options={'ordering': ['orden'], 'verbose_name': 'Etapa', 'verbose_name_plural': 'Etapas'},
        ),
        migrations.AddField(
            model_name='etapa',
            name='orden',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
