# Generated by Django 3.2 on 2022-03-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0012_auto_20220320_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartoetapa',
            name='orden',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
