# Generated by Django 3.2 on 2022-03-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0013_repartoetapa_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuesto',
            name='boleta_registro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Boleta Registro'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='boleta_rentas',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Boleta Rentas'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='fecha_boleta_registro',
            field=models.DateField(blank=True, help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Fecha Boleta Registro'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='fecha_boleta_rentas',
            field=models.DateField(blank=True, help_text='Introduzca la fecha en formato: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Fecha Boleta Rentas'),
        ),
    ]
