# Generated by Django 3.2 on 2022-03-24 02:11

from django.db import migrations, models
import stage.models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0014_auto_20220322_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='impuesto',
            name='file_boleta_registro',
            field=models.FileField(blank=True, null=True, upload_to=stage.models.registro_upload_to),
        ),
        migrations.AddField(
            model_name='impuesto',
            name='file_boleta_rentas',
            field=models.FileField(blank=True, null=True, upload_to=stage.models.rentas_upload_to),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='fecha_boleta_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Boleta Registro'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='fecha_boleta_rentas',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Boleta Rentas'),
        ),
    ]
