# Generated by Django 3.2 on 2022-04-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0015_auto_20220323_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacionetapa',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='repartoetapa',
            name='grupo_repartoetapa',
            field=models.CharField(choices=[('FAC', 'FACTURACION'), ('FIN', 'FINALIZACION'), ('JUR', 'JURIDICA'), ('PRO', 'PROCOTOLISTA')], default='PRO', max_length=3),
        ),
    ]
