# Generated by Django 3.2 on 2022-01-26 03:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grantor',
            fields=[
            ],
            options={
                'verbose_name': 'Otrogate',
                'verbose_name_plural': 'Otorgantes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('registration.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DataGrantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Puede agregar hasta 3 número de teléfono, separados por un / ', max_length=36, verbose_name='Teléfono')),
                ('address', models.CharField(max_length=150, verbose_name='Dirección')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos Otorgante',
                'verbose_name_plural': 'Datos Otorgantes',
            },
        ),
    ]
