# Generated by Django 3.2 on 2022-01-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_datagrantor_grantor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagrantor',
            name='address',
            field=models.CharField(help_text='Introduzca la dirección completa usando abreviaciones', max_length=150, verbose_name='Dirección'),
        ),
    ]
