# Generated by Django 3.2 on 2022-01-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_datagrantor_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grantor',
            options={'verbose_name': 'Otorgante', 'verbose_name_plural': 'Otorgantes'},
        ),
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.CharField(help_text='Debe ingresar una identificacion', max_length=15, null=True, unique=True, verbose_name='Identificacion'),
        ),
    ]
